mutation addItem($data: NotifyInput) {
  createNotify(data: $data) {
    title
    description
    rssInfoList {
      ago
      description
      publicURL
      publishedAt
      thumbnail
      title
      categories
    }
  }
}
